#!/bin/sh

if xrandr --listmonitors | grep -q eDP1; then
  # on eDP1, switch to external
  xrandr --output eDP1 --off --output DP2 --auto
  # change sound to external also
  pactl set-card-profile 0 output:hdmi-stereo-extra1
else
  # on external, switch to internal
  xrandr --output eDP1 --auto --output DP2 --off
  # return sound to internal speakers
  pactl set-card-profile 0 output:analog-stereo
fi
